"""Initial migration

Revision ID: 28b834a9fcbc
Revises:
Create Date: 2025-01-30 16:31:06.596548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b834a9fcbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorturl',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shortcode', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('update_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_shorturl_shortcode'), 'shorturl', ['shortcode'], unique=True)
    op.create_index(op.f('ix_shorturl_update_id'), 'shorturl', ['update_id'], unique=True)
    op.create_index(op.f('ix_shorturl_url'), 'shorturl', ['url'], unique=False)
    op.create_table('shorturlstats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shortcode', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_redirect', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redirect_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_shorturlstats_shortcode'), 'shorturlstats', ['shortcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shorturlstats_shortcode'), table_name='shorturlstats')
    op.drop_table('shorturlstats')
    op.drop_index(op.f('ix_shorturl_url'), table_name='shorturl')
    op.drop_index(op.f('ix_shorturl_update_id'), table_name='shorturl')
    op.drop_index(op.f('ix_shorturl_shortcode'), table_name='shorturl')
    op.drop_table('shorturl')
    # ### end Alembic commands ###
